name: Run stepwong for Multiple Accounts

on:
  workflow_dispatch:
  schedule:
    # 每天在UTC时间的 0点, 6点, 12点 运行 (对应北京时间 8点, 14点, 20点)
    - cron: '0 0,6,12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    # 使用矩阵策略，从ACCOUNTS_JSON这个secret中读取账号列表
    strategy:
      matrix:
        # fromJSON函数会将secret中的JSON字符串转换为可用的对象
        account: ${{ fromJSON(secrets.ACCOUNTS_JSON) }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Run script for ${{ matrix.account.user }}
        env:
          # 将矩阵中的当前账号信息设置为环境变量
          USER: ${{ matrix.account.user }}
          PASSWORD: ${{ matrix.account.password }}
          STEP: ${{ matrix.account.step }}
        run: |
          python main.py
