name: Run Stepwong for Multiple Accounts

on:
  # 这个选项允许你手动触发工作流
  workflow_dispatch:

  schedule:
    # 每天在UTC时间的 0点, 6点, 12点 运行 (对应北京时间 8点, 14点, 20点)
    - cron: '0 0,6,12 * * *'

jobs:
  # 第一个 Job：读取 Secret 并生成矩阵
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      # 将读取到的 Secret 内容作为输出，供下一个 Job 使用
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        # toJSON函数可以确保输出的是一个格式正确的JSON字符串
        run: echo "matrix=${{ toJSON(secrets.ACCOUNTS_JSON) }}" >> $GITHUB_OUTPUT

  # 第二个 Job：根据上一步生成的矩阵，为每个账号运行脚本
  run-script:
    # 'needs' 关键字确保这个 Job 必须在 generate-matrix 成功后才会开始
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      # 'fail-fast: false' 意味着即使一个账号失败了，其他账号的任务也会继续运行
      fail-fast: false
      # 关键改动：从上一个 Job 的 output 中读取矩阵信息
      matrix:
        account: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script for ${{ matrix.account.user }}
        env:
          USER: ${{ matrix.account.user }}
          PASSWORD: ${{ matrix.account.password }}
          STEP: ${{ matrix.account.step }}
        run: |
          python main.py
